### ISSUE TITLE
Random SSL: WRONG_VERSION_NUMBER from google calendar url

### ISSUE THREAD

**Issue by steevegl-axes** [jazzband/icalevents#59] opened 2019-09-08 02:49 UTC
I use icalevents 0.1.22 and google calendar url. I think I'm pulling to often but I tough the http cache was there for that...

```
...
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\site-packages\icalevents\icalevents.py", line 32, in events
    content = ICalDownload().data_from_url(url, apple_fix=fix_apple)
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\site-packages\icalevents\icaldownload.py", line 56, in data_from_url
    _, content = self.http.request(url)
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Steeve\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2508)
```

**Comment by eigenmannmartin** [comment] 2024-09-08 18:17
I am sorry, I cannot reproduce this. I am closing this. Please tell me if this is still pending.

**Closed by eigenmannmartin** 2024-09-08 18:17 UTC
