### ISSUE TITLE
Timezone handling issue

### ISSUE THREAD

**Issue by debackel** [jazzband/icalevents#12] opened 2018-02-25 17:15 UTC
I think there is an issue when handling timezones.
I have imported a calendar generated from gmail, with a timezone of Europe/Brussels (calendar and events).
An event was created to start at 8 AM (local time) on 30 MAR 2018.
When I display the event DTSTART, it show the time with a +01:00 time zone. 
But at that time of the year, the timezone in Belgium should be +02:00.

Using the method "events" of class "icalevents" indicates that you need to biais the "start" parameter to match the event.

See the attached files:
1/ The exported google calendar
2/ the code used for highlighting the issue.
3/ The output.

[MyCal2.txt](https://github.com/irgangla/icalevents/files/1756501/MyCal2.txt)
[essai2.txt](https://github.com/irgangla/icalevents/files/1756514/essai2.txt)
[output.txt](https://github.com/irgangla/icalevents/files/1756496/output.txt)

**Comment by lanewinfield** [comment] 2018-05-07 22:40
I'm also definitely showing a timezone issue. Looks like I need to manually adjust my queries to match my calendar's timezone.

**Comment by jc1518** [comment] 2018-06-07 23:56
+1. I have the timezone handling issue too.

**Comment by Hultner** [comment] 2019-01-21 15:41
I too had issues with timezones, It seems to always fallback to UTC and completely ignore TZID from DTSTART and DTEND, if I look into my calendar-files or open them i Calendar.app/Outlook/gCal the timezone is correct.

**Comment by Hultner** [comment] 2019-01-21 15:59
@irgangla I fixed my timezone issues by patching the normalize function. Above problem is caused by the library overwriting the tzid from DTSTART/DTEND (which parses fine) with UTC if it doesn't find another VTIMEZONE, I just commented out the overwriting for datetimes which already have an tzid which worked fine.

Offending line:
https://github.com/irgangla/icalevents/blob/182aba819c465e32dcf66ee995fd7a3cf7a129af/icalevents/icalparser.py#L167

My local version which works (get the same timezone out as the one I put in when I create the ical-file with the icalendar package). 
<img width="688" alt="screen shot 2019-01-21 at 16 58 32" src="https://user-images.githubusercontent.com/2669034/51485231-da3ccf00-1d9d-11e9-99db-5e85564d99a7.png">

**Comment by ndw** [comment] 2019-03-13 21:10
That fix helps, but there's another bug. If a repeating event crosses over from when DST was not in effect to when it is in effect, the adjustment gets lost. A meeting started at 08:00:00-08:00 (8:00am America/Los_Angeles in January) is still reported as 08:00:00-08:00 in March when it should be 08:00:00-07:00.

**Comment by ndw** [comment] 2019-03-13 23:49
I believe I've fixed the repeating-events-crossing-daylight-saving-time boundary issue. I don't know what else I might have broken. "Works for me :smile:"

https://github.com/ndw/icalevents

**Comment by greuff** [comment] 2020-03-03 19:30
I had the same problem and the fix from @ndw works perfectly. Would be great to have this merged.

**Comment by irgangla** [comment] 2020-03-03 21:04
There are merge conflicts and I have no time to fix it. If you provide a working pull request I will merge it.

**Comment by ndw** [comment] 2020-03-04 10:48
Hmm. Was that true when I created it? Doesn't matter, I suppose. I'll see if I can get a clean PR, but it may take a few days.

**Comment by ndw** [comment] 2020-03-09 13:19
The good news is I was able to get a clean PR. The bad news is it fails a bunch of tests. It's all a bit complicated. Timezones are required to deal with DST boundaries, but repeating all day events must not have timezones (or RRULE checks fail). Also, python is fussy about comparisons between timezone naive and timezone aware datetime values. I'm still working on it, but it's not going smoothly.

**Closed** 2021-10-17 16:33 UTC
