### ISSUE TITLE
Add encoding parameter to events, etc.

### ISSUE THREAD

**Issue by webdeck** [jazzband/icalevents#104] opened 2022-02-11 01:01 UTC
I have a calendar URL that is encoded in latin_1 (olympic events provided by ecal.com)

It would be great if the top level events() API allowed overriding the encoding of UTF-8.  Instead, I have to invoke ICalDownload directly so that I can specify the encoding.

**Comment by eigenmannmartin** [comment] 2024-09-09 11:44
Thank you very much for this bug report. I think this is a duplicate of this one: https://github.com/jazzband/icalevents/issues/128

**Closed by eigenmannmartin** 2024-09-09 11:44 UTC
